on:
  push:
    branches: [ master ]

name: ğŸš€ Deploy orRank
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ğŸ› Validate composer.json and composer.lock
      run: composer validate --strict

    - name: ğŸ“‚ Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: ğŸ”¨ Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: ğŸ”¨ Setup Laravel move directory
      run: mv public public_html
        
    - name: ğŸš€ Deploy ğŸ“‚ Sync files ğŸ‰
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.orrank.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/Laravel/
