on:
  push:
    branches: [master]

name: ğŸš€ Deploy orRank
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ› Validate composer.json and composer.lock
        run: composer validate --strict

      - name: ğŸ”¨ Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: ğŸ”¨ Install NPM dependencies Setup Laravel move directory
        run: npm install && npm run dev

      # - name: ğŸ”¨ Setup Laravel directory structure
      #   run: mv

      - name: ğŸš€ Deploy ğŸ“‚ Sync files ğŸ‰
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.orrank.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/Laravel/
