on:
  push:
    branches: [master]

name: ğŸš€ Deploy orRank
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ› Validate composer.json and composer.lock
        run: composer validate --strict

      - name: ğŸ”¨ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: ğŸ”¨ Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: ğŸš€ Execute tests
        run: vendor/bin/phpunit --verbose
      #- name: ğŸ”¨ Install NPM dependencies Setup Laravel move directory
      #  run: npm install && npm run dev

      - name: ğŸ”¨ Laravel configuration Cache clear
        run: php artisan config:cache

      #- name: ğŸ”¨ Remove public
      #  run: rm -rf public

      - name: ğŸš€ Deploy ğŸ“‚ Sync files ğŸ‰
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.orrank.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/Laravel/
      #    exclude: vendor/**
      #      - vendor/**/*
      #      - node_modules/**
      #      - node_modules/**/*
      #      - .github/**/*
      #      - .git/**/*
      #      - public/**/*
      #      - bootstrap/**
      #      - bootstrap/**/*
